## 필수과제1
- 강남구 말고 다른 구로 스타벅스 매장 거리 계산 - Folium으로 시각화 ( 더 패키지 사용해서 예쁘게 하셔도 됩니다! )
- 여러분들이 지정한 start_point에서 가장가까운 매장과 가장 먼 매장은 어디인지? 리스트 출력하는 것

In [31]:
##스타벅스 데이터를 가지고 와서 계산해 보자!
import numpy as np
import pandas as pd 
df = pd.read_csv('C:/Users/user/BDA_Data/Dataset/Starbucks_Seoul.csv')

In [17]:
df

,name,address,gu_name,latitude,longitude
0,GS타워,서울특별시 강남구 논현로 508 (역삼동),강남구,37.501859,127.037278
1,SSG마켓도곡R,"서울특별시 강남구 언주로30길 57, 타워팰리스Ⅱ F 지하1층 (도곡동)",강남구,37.490298,127.054895
2,W-Mall,서울특별시 금천구 디지털로 188 (가산동),금천구,37.477305,126.887691
3,가든파이브,서울특별시 송파구 충민로 10 (문정동) 가든파이브툴,송파구,37.478232,127.119370
4,가락본동,서울특별시 송파구 송파대로30길 13 (가락동),송파구,37.494895,127.118785
...,...,...,...,...,...
516,황학사거리,"서울특별시 성동구 왕십리로 410 (하왕십리동, 센트라스)",성동구,37.567644,127.023697
517,황학캐슬,서울특별시 중구 청계천로 400 (황학동) 롯데캐슬베네치아,중구,37.571240,127.022905
518,회기역사거리,서울특별시 동대문구 이문로 37 (회기동),동대문구,37.590784,127.056098
519,회현역,서울특별시 중구 퇴계로 72 (회현동) 리더스뷰남산,중구,37.558981,126.980747
520,효창공원앞역,"서울특별시 용산구 백범로 313 (효창동, 용산 롯데캐슬 센터포레)",용산구,37.539305,126.963060

In [33]:
## 위도 경도로 거리 계산
## 폴리옴으로 시각화까지 해보자!
from geopy.distance import geodesic
import folium

In [42]:
df_ydp=df[df['gu_name']=='영등포구']

In [43]:
#유클리디안 거리로 계산
#cdist(XA, XB, metric='euclidean')

pd.DataFrame(distance.cdist(df_ydp[['latitude','longitude']],df_ydp[['latitude','longitude']], metric= 'euclidean'))

,0,1,2,3,4,5,6,7,8,9,...,24,25,26,27,28,29,30,31,32,33
0,0.000000,0.003607,0.020211,0.016003,0.018159,0.016009,0.012110,0.031740,0.026402,0.016708,...,0.014115,0.011007,0.015243,0.015269,0.027386,0.016888,0.020915,0.020915,0.020648,0.026075
1,0.003607,0.000000,0.018459,0.014107,0.016394,0.016868,0.012142,0.028446,0.022906,0.017229,...,0.014695,0.011193,0.012220,0.011695,0.024241,0.013345,0.017313,0.017313,0.017046,0.022488
2,0.020211,0.018459,0.000000,0.004369,0.002068,0.035301,0.030343,0.018656,0.018072,0.035554,...,0.033075,0.029499,0.009633,0.019056,0.032232,0.020394,0.018503,0.018503,0.018394,0.020534
3,0.016003,0.014107,0.004369,0.000000,0.002332,0.030936,0.025976,0.019571,0.017320,0.031185,...,0.028706,0.025130,0.006393,0.015515,0.029235,0.017017,0.016141,0.016141,0.015983,0.019157
4,0.018159,0.016394,0.002068,0.002332,0.000000,0.033241,0.028301,0.019220,0.017843,0.033505,...,0.031020,0.027449,0.008149,0.017498,0.030972,0.018922,0.017514,0.017514,0.017381,0.020025
5,0.016009,0.016868,0.035301,0.030936,0.033241,0.000000,0.005436,0.042145,0.035411,0.001678,...,0.002381,0.005957,0.027941,0.022271,0.026618,0.022853,0.028563,0.028563,0.028329,0.033566
6,0.012110,0.012142,0.030343,0.025976,0.028301,0.005436,0.000000,0.036722,0.030026,0.005258,...,0.003059,0.001152,0.022627,0.016879,0.022618,0.017540,0.023212,0.023212,0.022974,0.028277
7,0.031740,0.028446,0.018656,0.019571,0.019220,0.042145,0.036722,0.000000,0.007161,0.041638,...,0.039778,0.036394,0.016683,0.019927,0.025359,0.019665,0.013982,0.013982,0.014170,0.010258
8,0.026402,0.022906,0.018072,0.017320,0.017843,0.035411,0.030026,0.007161,0.000000,0.034809,...,0.033065,0.029788,0.012467,0.013147,0.018717,0.012673,0.006926,0.006926,0.007137,0.003510
9,0.016708,0.017229,0.035554,0.031185,0.033505,0.001678,0.005258,0.041638,0.034809,0.000000,...,0.002593,0.006057,0.027873,0.021716,0.025289,0.022176,0.027918,0.027918,0.027692,0.032832
10,0.025920,0.024204,0.005747,0.010101,0.007814,0.041035,0.036043,0.018344,0.019929,0.041267,...,0.038800,0.035215,0.014560,0.023838,0.036180,0.024978,0.022107,0.022107,0.022054,0.022958
11,0.022962,0.020934,0.003208,0.006962,0.004975,0.037648,0.032552,0.016222,0.016687,0.037799,...,0.035374,0.031769,0.010690,0.019924,0.032342,0.021060,0.018307,0.018307,0.018243,0.019516
12,0.019129,0.015522,0.018873,0.016061,0.017670,0.026336,0.020989,0.016141,0.009137,0.025691,...,0.024008,0.020821,0.009672,0.004245,0.013364,0.003537,0.002228,0.002228,0.002002,0.007393
13,0.019129,0.015522,0.018873,0.016061,0.017670,0.026336,0.020989,0.016141,0.009137,0.025691,...,0.024008,0.020821,0.009672,0.004245,0.013364,0.003537,0.002228,0.002228,0.002002,0.007393
14,0.007965,0.008527,0.026978,0.022619,0.024915,0.008346,0.004211,0.035147,0.028811,0.008825,...,0.006244,0.003073,0.020003,0.015877,0.024243,0.016928,0.022276,0.022276,0.022020,0.027513
15,0.014157,0.014194,0.032326,0.027962,0.030291,0.004182,0.002069,0.038148,0.031343,0.003504,...,0.002171,0.003151,0.024445,0.018231,0.022695,0.018736,0.024467,0.024467,0.024238,0.029427
16,0.007147,0.008195,0.026631,0.022291,0.024564,0.008896,0.005301,0.035472,0.029264,0.009564,...,0.006973,0.004149,0.020020,0.016472,0.025334,0.017613,0.022838,0.022838,0.022578,0.028098
17,0.007865,0.009040,0.027466,0.023129,0.025398,0.008145,0.004950,0.036279,0.030036,0.008893,...,0.006314,0.003814,0.020869,0.017190,0.025710,0.018293,0.023572,0.023572,0.023313,0.028824
18,0.003824,0.002001,0.020400,0.016039,0.018339,0.014904,0.010141,0.029641,0.023816,0.015237,...,0.012711,0.009195,0.013751,0.011887,0.023571,0.013403,0.017873,0.017873,0.017606,0.023121
19,0.005422,0.008112,0.025626,0.021424,0.023577,0.011580,0.009103,0.036513,0.030752,0.012619,...,0.010136,0.007967,0.020313,0.018577,0.028764,0.019952,0.024730,0.024730,0.024463,0.029996
20,0.007949,0.007954,0.026310,0.021942,0.024255,0.009014,0.004247,0.033992,0.027602,0.009278,...,0.006766,0.003242,0.019051,0.014627,0.023036,0.015653,0.021031,0.021031,0.020776,0.026260
21,0.001559,0.004745,0.021764,0.017561,0.019713,0.014700,0.011105,0.033120,0.027650,0.015486,...,0.012902,0.009973,0.016700,0.016152,0.027739,0.017704,0.021986,0.021986,0.021718,0.027191
22,0.002327,0.003225,0.021396,0.017085,0.019329,0.014196,0.009964,0.031588,0.025885,0.014757,...,0.012171,0.008894,0.015444,0.014051,0.025490,0.015558,0.020019,0.020019,0.019751,0.025259
23,0.012353,0.013357,0.031816,0.027461,0.029751,0.003660,0.003481,0.039541,0.032997,0.004610,...,0.002267,0.003270,0.024776,0.019882,0.026086,0.020687,0.026274,0.026274,0.026028,0.031416
24,0.014115,0.014695,0.033075,0.028706,0.031020,0.002381,0.003059,0.039778,0.033065,0.002593,...,0.000000,0.003616,0.025590,0.019921,0.024864,0.020540,0.026234,0.026234,0.025998,0.031267
25,0.011007,0.011193,0.029499,0.025130,0.027449,0.005957,0.001152,0.036394,0.029788,0.006057,...,0.003616,0.000000,0.021984,0.016654,0.023137,0.017425,0.023033,0.023033,0.022789,0.028159
26,0.015243,0.012220,0.009633,0.006393,0.008149,0.027941,0.022627,0.016683,0.012467,0.027873,...,0.025590,0.021984,0.000000,0.009425,0.022865,0.010784,0.009895,0.009895,0.009715,0.013551
27,0.015269,0.011695,0.019056,0.015515,0.017498,0.022271,0.016879,0.019927,0.013147,0.021716,...,0.019921,0.016654,0.009425,0.000000,0.014156,0.001801,0.006409,0.006409,0.006158,0.011636
28,0.027386,0.024241,0.032232,0.029235,0.030972,0.026618,0.022618,0.025359,0.018717,0.025289,...,0.024864,0.023137,0.022865,0.014156,0.000000,0.012431,0.014104,0.014104,0.014139,0.015253
29,0.016888,0.013345,0.020394,0.017017,0.018922,0.022853,0.017540,0.019665,0.012673,0.022176,...,0.020540,0.017425,0.010784,0.001801,0.012431,0.000000,0.005752,0.005752,0.005536,0.010739
30,0.020915,0.017313,0.018503,0.016141,0.017514,0.028563,0.023212,0.013982,0.006926,0.027918,...,0.026234,0.023033,0.009895,0.006409,0.014104,0.005752,0.000000,0.000000,0.000268,0.005274
31,0.020915,0.017313,0.018503,0.016141,0.017514,0.028563,0.023212,0.013982,0.006926,0.027918,...,0.026234,0.023033,0.009895,0.006409,0.014104,0.005752,0.000000,0.000000,0.000268,0.005274
32,0.020648,0.017046,0.018394,0.015983,0.017381,0.028329,0.022974,0.014170,0.007137,0.027692,...,0.025998,0.022789,0.009715,0.006158,0.014139,0.005536,0.000268,0.000268,0.000000,0.005539
33,0.026075,0.022488,0.020534,0.019157,0.020025,0.033566,0.028277,0.010258,0.003510,0.032832,...,0.031267,0.028159,0.013551,0.011636,0.015253,0.010739,0.005274,0.005274,0.005539,0.000000

In [44]:
city_ydp=distance.cdist(df_ydp[['latitude','longitude']],df_ydp[['latitude','longitude']], metric= 'cityblock')

In [45]:
city_ydp

array([[0.        , 0.005096  , 0.024511  , ..., 0.029437  , 0.029064  ,
        0.03649098],
       [0.005096  , 0.        , 0.024273  , ..., 0.024341  , 0.023968  ,
        0.03139498],
       [0.024511  , 0.024273  , 0.        , ..., 0.021624  , 0.021689  ,
        0.02178798],
       ...,
       [0.029437  , 0.024341  , 0.021624  , ..., 0.        , 0.000373  ,
        0.00705398],
       [0.029064  , 0.023968  , 0.021689  , ..., 0.000373  , 0.        ,
        0.00742698],
       [0.03649098, 0.03139498, 0.02178798, ..., 0.00705398, 0.00742698,
        0.        ]])

In [46]:
dist_city_ydp =pd.DataFrame(data=city_ydp, columns = df_gn['name'])
dist_city_ydp.set_index(df_gn['name'], inplace=True)

In [47]:
dist_city_ydp

name,국회대로,국회의사당역,당산,당산대로,당산역,동여의도,롯데캐슬여의도,문래동,문래역,샛강역,...,여의도호성,여의도화재보험,영등포KT,영등포본동,영등포신길DT,영등포역,타임스퀘어,타임스퀘어B2,타임스퀘어R,하이테크시티
name,,,,,,,,,,,,,,,,,,,,,
국회대로,0.000000,0.005096,0.024511,0.018606,0.021846,0.022557,0.016827,0.040555,0.035906,0.023627,...,0.019961,0.015370,0.018311,0.021537,0.035170,0.023709,0.029437,0.029437,0.029064,0.036491
국회의사당역,0.005096,0.000000,0.024273,0.018368,0.021608,0.022795,0.017065,0.035459,0.030810,0.023865,...,0.020199,0.015608,0.013215,0.016441,0.030074,0.018613,0.024341,0.024341,0.023968,0.031395
당산,0.024511,0.024273,0.000000,0.005905,0.002665,0.047068,0.041338,0.025852,0.021203,0.048139,...,0.044472,0.039881,0.013136,0.026068,0.040729,0.027400,0.021624,0.021624,0.021689,0.021788
당산대로,0.018606,0.018368,0.005905,0.000000,0.003240,0.041163,0.035433,0.027671,0.023022,0.042234,...,0.038567,0.033976,0.007231,0.020163,0.034824,0.021495,0.016553,0.016553,0.016180,0.023607
당산역,0.021846,0.021608,0.002665,0.003240,0.000000,0.044404,0.038673,0.027056,0.022407,0.045474,...,0.041807,0.037216,0.010471,0.023403,0.038064,0.024735,0.018959,0.018959,0.019024,0.022992
동여의도,0.022557,0.022795,0.047068,0.041163,0.044404,0.000000,0.005731,0.042491,0.037842,0.002118,...,0.002596,0.007187,0.033932,0.023473,0.037106,0.025645,0.031373,0.031373,0.031000,0.038427
롯데캐슬여의도,0.016827,0.017065,0.041338,0.035433,0.038673,0.005731,0.000000,0.037366,0.032717,0.006801,...,0.003134,0.001457,0.028202,0.018348,0.031981,0.020520,0.026248,0.026248,0.025875,0.033302
문래동,0.040555,0.035459,0.025852,0.027671,0.027056,0.042491,0.037366,0.000000,0.008997,0.042867,...,0.040348,0.038095,0.022244,0.020796,0.035457,0.022128,0.016352,0.016352,0.016417,0.013927
문래역,0.035906,0.030810,0.021203,0.023022,0.022407,0.037842,0.032717,0.008997,0.000000,0.035724,...,0.035699,0.033446,0.017595,0.014369,0.026460,0.013131,0.007355,0.007355,0.007420,0.004930
샛강역,0.023627,0.023865,0.048139,0.042234,0.045474,0.002118,0.006801,0.042867,0.035724,0.000000,...,0.003666,0.008257,0.035002,0.022070,0.034988,0.023526,0.029255,0.029255,0.028882,0.036309
선유도역,0.031963,0.031725,0.007452,0.013357,0.010117,0.054520,0.048790,0.022608,0.021721,0.055591,...,0.051924,0.047333,0.020588,0.033520,0.048181,0.034852,0.029076,0.029076,0.029141,0.026651
선유동이레빌딩,0.026486,0.026248,0.004085,0.007880,0.005289,0.049043,0.043313,0.021767,0.017118,0.050114,...,0.046447,0.041856,0.015111,0.028043,0.042704,0.029375,0.023599,0.023599,0.023664,0.021174
신세계영등포B,0.027039,0.021943,0.023668,0.017763,0.021003,0.028975,0.023850,0.018396,0.009399,0.026857,...,0.026832,0.024579,0.010532,0.005502,0.017061,0.003732,0.002398,0.002398,0.002025,0.009452
신세계영등포B2,0.027039,0.021943,0.023668,0.017763,0.021003,0.028975,0.023850,0.018396,0.009399,0.026857,...,0.026832,0.024579,0.010532,0.005502,0.017061,0.003732,0.002398,0.002398,0.002025,0.009452
여의도,0.011194,0.011432,0.035705,0.029800,0.033040,0.011364,0.005633,0.039299,0.034650,0.012434,...,0.008767,0.004176,0.022569,0.020281,0.033914,0.022453,0.028181,0.028181,0.027808,0.035235
여의도ABL타워,0.019752,0.019990,0.044263,0.038358,0.041598,0.005206,0.002925,0.038991,0.032636,0.003875,...,0.003063,0.004382,0.031127,0.018267,0.031900,0.020439,0.026167,0.026167,0.025794,0.033221
여의도IFC(1F),0.010106,0.010344,0.034617,0.028712,0.031952,0.012451,0.006721,0.040687,0.036038,0.013522,...,0.009855,0.005264,0.021481,0.021669,0.035302,0.023841,0.029569,0.029569,0.029196,0.036623
여의도IFC몰(L1)R,0.011092,0.011330,0.035603,0.029698,0.032938,0.011465,0.005735,0.041381,0.036732,0.012536,...,0.008869,0.004278,0.022467,0.022363,0.035996,0.024535,0.030263,0.030263,0.029890,0.037317
여의도KBS R,0.004757,0.002809,0.027082,0.021177,0.024417,0.019986,0.014256,0.035798,0.031149,0.021056,...,0.017390,0.012799,0.013946,0.016780,0.030413,0.018952,0.024680,0.024680,0.024307,0.031734
여의도공원R,0.006352,0.009390,0.030863,0.024958,0.028198,0.016205,0.010475,0.044849,0.040200,0.017276,...,0.013609,0.009018,0.022605,0.025831,0.039464,0.028003,0.033731,0.033731,0.033358,0.040785
여의도역R,0.010822,0.011060,0.035333,0.029428,0.032668,0.011735,0.006005,0.037513,0.032864,0.012805,...,0.009139,0.004548,0.022197,0.018495,0.032128,0.020667,0.026395,0.026395,0.026022,0.033449
여의도의사당,0.001778,0.006400,0.026289,0.020384,0.023624,0.020779,0.015049,0.041859,0.037210,0.021849,...,0.018183,0.013592,0.019615,0.022841,0.036474,0.025013,0.030741,0.030741,0.030368,0.037795
여의도일신,0.002814,0.003390,0.027325,0.021420,0.024660,0.019743,0.014013,0.038849,0.034200,0.020814,...,0.017147,0.012556,0.016605,0.019831,0.033464,0.022003,0.027731,0.027731,0.027358,0.034785
여의도한양증권,0.017386,0.017624,0.041897,0.035992,0.039232,0.005171,0.004891,0.042257,0.037608,0.006242,...,0.002575,0.004162,0.028761,0.023239,0.036872,0.025411,0.031139,0.031139,0.030766,0.038193
여의도호성,0.019961,0.020199,0.044472,0.038567,0.041807,0.002596,0.003134,0.040348,0.035699,0.003666,...,0.000000,0.004591,0.031336,0.021330,0.034963,0.023502,0.029230,0.029230,0.028857,0.036284
여의도화재보험,0.015370,0.015608,0.039881,0.033976,0.037216,0.007187,0.001457,0.038095,0.033446,0.008257,...,0.004591,0.000000,0.026745,0.019077,0.032710,0.021249,0.026977,0.026977,0.026604,0.034031
영등포KT,0.018311,0.013215,0.013136,0.007231,0.010471,0.033932,0.028202,0.022244,0.017595,0.035002,...,0.031336,0.026745,0.000000,0.012932,0.027593,0.014264,0.011126,0.011126,0.010753,0.018180
영등포본동,0.021537,0.016441,0.026068,0.020163,0.023403,0.023473,0.018348,0.020796,0.014369,0.022070,...,0.021330,0.019077,0.012932,0.000000,0.014661,0.002172,0.007900,0.007900,0.007527,0.014954
영등포신길DT,0.035170,0.030074,0.040729,0.034824,0.038064,0.037106,0.031981,0.035457,0.026460,0.034988,...,0.034963,0.032710,0.027593,0.014661,0.000000,0.013329,0.019105,0.019105,0.019040,0.021530
영등포역,0.023709,0.018613,0.027400,0.021495,0.024735,0.025645,0.020520,0.022128,0.013131,0.023526,...,0.023502,0.021249,0.014264,0.002172,0.013329,0.000000,0.005776,0.005776,0.005711,0.012782
타임스퀘어,0.029437,0.024341,0.021624,0.016553,0.018959,0.031373,0.026248,0.016352,0.007355,0.029255,...,0.029230,0.026977,0.011126,0.007900,0.019105,0.005776,0.000000,0.000000,0.000373,0.007054
타임스퀘어B2,0.029437,0.024341,0.021624,0.016553,0.018959,0.031373,0.026248,0.016352,0.007355,0.029255,...,0.029230,0.026977,0.011126,0.007900,0.019105,0.005776,0.000000,0.000000,0.000373,0.007054
타임스퀘어R,0.029064,0.023968,0.021689,0.016180,0.019024,0.031000,0.025875,0.016417,0.007420,0.028882,...,0.028857,0.026604,0.010753,0.007527,0.019040,0.005711,0.000373,0.000373,0.000000,0.007427
하이테크시티,0.036491,0.031395,0.021788,0.023607,0.022992,0.038427,0.033302,0.013927,0.004930,0.036309,...,0.036284,0.034031,0.018180,0.014954,0.021530,0.012782,0.007054,0.007054,0.007427,0.000000

In [48]:
## 지도에 좌표를 찍어서 확인해 보자!

def cal_euc_dis(row1, row2):
    pnt1 = np.array([row1['latitude'],row1['longitude']])
    pnt2 = np.array([row2['latitude'],row2['longitude']])
    return np.linalg.norm(pnt1- pnt2)

In [49]:
## 지도에 기준점이 필요하다. 
## 기준점은 평균으로 잡고 각 거리를 계산해 보자

map_center =[df_ydp['latitude'].mean(), df_ydp['longitude'].mean()]

#folium 시각화를 해서 지도 위치 시각화

m =folium.Map(location=map_center, zoom_start=10)

In [50]:
## 모든 위치에 있는 스타벅스 영등포구 매장들 마커 찍어서 거리 계산하면 된다.

for idx, row in df_ydp.iterrows():
    folium.Marker(location = [row['latitude'], row['longitude']], popup=row['name']).add_to(m)
    
## 첫 번째 스타트할 포인트
start_point = df_ydp.iloc[0]

## 첫 번째 지점과 나머지 다른 지점들의 거리를 계산해서 지도에 표시하는 것
for idx,row in df_ydp.iterrows():
    if start_point['name'] != row['name']:
        dis = cal_euc_dis(start_point, row)
        folium.PolyLine(locations = [[start_point['latitude'], start_point['longitude']],
                                    [row['latitude'],row['longitude']]]).add_to(m)

In [51]:
m

In [55]:
for store in distance_list:
    print(store)

('여의도의사당', 0.0015591183406043652)
('여의도일신', 0.0023269112574380592)
('국회의사당역', 0.003607343898217874)
('여의도KBS R', 0.0038235513596652877)
('여의도공원R', 0.0054215468272333514)
('여의도IFC(1F)', 0.007146630674655807)
('여의도IFC몰(L1)R', 0.00786494564506894)
('여의도역R', 0.007948881933956141)
('여의도', 0.007964811783465623)
('여의도화재보험', 0.011006554865173053)
('롯데캐슬여의도', 0.01211004934835148)
('여의도한양증권', 0.01235252605744172)
('여의도호성', 0.014115317389277559)
('여의도ABL타워', 0.01415687825757996)
('영등포KT', 0.015242758050955154)
('영등포본동', 0.015268703579546081)
('당산대로', 0.0160028230634573)
('동여의도', 0.016009064096621225)
('샛강역', 0.016707662756050404)
('영등포역', 0.01688848311602087)
('당산역', 0.018158857259756776)
('신세계영등포B', 0.0191287502205465)
('신세계영등포B2', 0.0191287502205465)
('당산', 0.020210978823410185)
('타임스퀘어R', 0.020647999660988462)
('타임스퀘어', 0.020914967583055846)
('타임스퀘어B2', 0.020914967583055846)
('선유동이레빌딩', 0.022961893867888168)
('선유도역', 0.02592034122075298)
('하이테크시티', 0.02607500050516836)
('문래역', 0.026402077569772368)
('영등포신길DT', 0.02738569356434481)
('문래동', 0.03173993656263839)

In [54]:
# 가장 가까운 지점과 가장 먼 지점 찾기
distance_list.sort(key=lambda x: x[1])
closest_store = distance_list[0]
farthest_store = distance_list[-1]

# 결과 출력
print("가장 가까운 지점:", closest_store)
print("가장 먼 지점:", farthest_store)

가장 가까운 지점: ('여의도의사당', 0.0015591183406043652)
가장 먼 지점: ('문래동', 0.03173993656263839)